metadata:
  labels:
    app: vertx-dns-cluster-test-jgroups
  name: vertx-dns-cluster-test-jgroups
spec:
  clusterIP: None
  selector:
    app: vertx-dns-cluster-test
  ports:
    - name: infinispan
      port: 8888
      targetPort: 8888
      protocol: TCP